services:
  - type: worker
    name: skystrife-indexer
    plan: standard
    region: ohio
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod-skystrife-indexer-db
          property: connectionString
      - key: RPC_HTTP_URL
        value: https://rpc.redstonechain.com
      - key: DEBUG
        value: mud:store-sync:createStoreSync
      - key: STORE_ADDRESS
        value: "0xc6b640ea79444c1bb0c6924771cc7432fb0bddd6"
      - key: START_BLOCK
        value: 868954

  - type: web
    name: skystrife-indexer-api
    plan: pro
    region: ohio
    runtime: docker
    domains:
      - indexer.skystrife.xyz
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    dockerCommand: pnpm tsx bin/postgres-frontend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod-skystrife-indexer-db-replica
          property: connectionString
      - key: DEBUG
        value: mud:*

databases:
  - name: prod-skystrife-indexer-db
    plan: pro
    region: ohio
    readReplicas:
      - name: prod-skystrife-indexer-db-replica
